name: Build Plugin

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
    inputs:
      build_configuration:
        description: 'Build configuration'
        # Default value if no value is explicitly provided
        default: 'Release'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/download-artifact@v2
    
    - name: Download Valheim
      run: |
        dotnet contrib/depotdownloader-2.3.6/DepotDownloader.dll -app 896660 -os windows -filelist .depot-downloader-file-list.txt -dir serverfiles
        
    - name: build
      run: |
        xcopy /E /I lib ..\ValheimLibs
        xcopy /I serverfiles\valheim_server_Data\Managed\* ..\ValheimLibs\
        msbuild /t:Restore,Build -p:Configuration=${{ github.event.inputs.build_configuration }}
        
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: serverside-simulations-x
        path: bin\Release\Serverside_Simulations.dll

      
